# =====================================
# Actuator
# =====================================
logging:
  level:
    org.springframework.cloud.config.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

my:
  local:
    test:
      key: Test
